### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by danwalmsley** [darrenstarr/VtNetCore.UWP#2]
error: Server does not allow request for unadvertised object 09d0a30329dab58ba4f6711d735eee1e8501cb1f
Fetched in submodule path 'modules/SSH.NET', but it did not contain 09d0a30329dab58ba4f6711d735eee1e8501cb1f. Direct fetching of that commit failed

**Comment by darrenstarr** [comment]
I think this is sorted out now. Soon I'll switch to making the wrapper apps separate respositories which should sort this out permanently.
